repos:
  - repo: local
    hooks:
      # Run the formatter.
      - id: ruff-format
        name: Ruff Format
        entry: ruff format
        language: system
        types: [python]
        pass_filenames: true

      # Run the linter.
      - id: ruff-linter
        name: Ruff Linter
        entry: ruff check --fix
        language: system
        types: [python]
        pass_filenames: true

      # Run type checker
      - id: mypy
        name: Mypy type checker
        entry: mypy
        language: system
        types: [python]
        pass_filenames: true