repos:
  # Ruff Python formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      # Run the linter.
      - id: ruff
        name: Ruff Linter
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        stages: [pre-commit]
  # Mypy static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      # Run type checker
      - id: mypy
        name: Mypy type checker
        stages: [pre-commit]